#pragma once

#include <windows.h>

#define IO_GET_CLIENTADDRESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x555, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IO_READ_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x778, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IO_WRITE_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x779, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _IO_READ_REQUEST {

	ULONG ProcessId;
	ULONG Address;
	PVOID pBuff;
	UCHAR Size;

} KERNEL_READ_REQUEST, * PKERNEL_READ_REQUEST;

typedef struct _IO_WRITE_REQUEST {

	ULONG ProcessId;
	ULONG Address;
	PVOID pBuff;
	UCHAR Size;

} KERNEL_WRITE_REQUEST, * PKERNEL_WRITE_REQUEST;